Accept Authoritative DNS Responses
adafruit/Adafruit_CircuitPython_Wiznet5k pull request #26
Opened 2020-09-28 22:40 UTC by kevinaj

By adding 0x8580 as an allowed response flag, responses with the 'authoritative' bit set to 1 will now be treated as a valid response

This works a temporary fix to #25 but to be correct, the flags probably need to be parsed individually.

2020-09-30 14:40 UTC, brentru requested changes
@kevinaj  Thanks for adding this, I'll merge it in. To clarify - this sets the `AA` bit, correct? What would the advantage to parsing the flags individually be?

Also - PyLint is failing here (https://github.com/adafruit/Adafruit_CircuitPython_Wiznet5k/pull/26/checks?check_run_id=1179193313#step:12:8). You'll need to fix this before I can merge in.

2020-09-30 21:23 UTC, kevinaj commented
@brentru Fixed the code to make pylint happy. 

Technically, it doesn't _set_ the AA bit--it reads it. If the AA bit is set, the response is still valid and should be accepted.

As to why the flags should be processed individually, there are a lot of possible combinations of flags that would still result in a valid response that are not currently accepted. I think it's easiest to show with a diagram from Wireshark for reference:
```
Flags: 0x8580 Standard query response, No error
        1... .... .... .... = Response: Message is a response
        .000 0... .... .... = Opcode: Standard query (0)
        .... .1.. .... .... = Authoritative: Server is an authority for domain
        .... ..0. .... .... = Truncated: Message is not truncated
        .... ...1 .... .... = Recursion desired: Do query recursively
        .... .... 1... .... = Recursion available: Server can do recursive queries
        .... .... .0.. .... = Z: reserved (0)
        .... .... ..0. .... = Answer authenticated: Answer/authority portion was not authenticated by the server
        .... .... ...0 .... = Non-authenticated data: Unacceptable
        .... .... .... 0000 = Reply code: No error (0)
```
For example, a response from a server that does not do recursive queries would not be accepted with the current code as the value of `flags` would be 0x8500.

I'm no DNS expert and I'm probably leaving out something important, but I'd suggest validating the flags by ensuring that:
1. bit 1 (Response) is set to `1`
2. bit 7 (Truncated) is set to `0`
3. last 4 bits (Reply code) are `0000`

2020-10-07 23:09 UTC, kevinaj reviewed
Fixed in latest commit

2020-10-08 13:18 UTC, brentru commented
@kevinaj I'm going to review/test this tomorrow if that's ok, haven't set up my PoE yet.

Does this seem to fix https://github.com/adafruit/Adafruit_CircuitPython_Wiznet5k/issues/19 as well?

2020-10-08 15:04 UTC, kevinaj commented
I didn't check to see if it fixes #19 or not. I'll run a quick test tonight.

2020-10-09 03:11 UTC, kevinaj commented
This does NOT fix #19. The following still occurs when testing `http://www.wikipedia.de`: 

```
* DNS ERROR: Did not receive DNS response!
* DNS ERROR: Failed to resolve DNS response, retrying...
*** Closing socket #0
* Resolved IP:  -1
Request failed, retrying...
 Failed to resolve hostname!
```

2020-10-09 14:03 UTC, brentru commented
@kevinaj  Thanks for testing - I tested that this morning as well, same result. LGTM, thank you for the PR!

2020-10-09 14:04 UTC, brentru approved these changes

2020-10-09 14:04 UTC, merged