Fix documentation
adafruit/Adafruit_CircuitPython_Wiznet5k pull request #55
Opened 2022-03-28 15:33 UTC by Neradoc

Missing new lines for parameters list.
Lists all submodules in APIs.

2022-03-28 19:15 UTC, tekktrik commented on adafruit_wiznet5k/adafruit_wiznet5k_ntp.py
> -`wiznet5k_ntp`
Nice catch!

2022-03-28 19:15 UTC, tekktrik commented on adafruit_wiznet5k/adafruit_wiznet5k_socket.py
> -        :returns a tuple (nbytes, address) where address is a tuple (ip, port)
Double nice catch!

2022-03-28 19:18 UTC, brentru approved these changes

2022-03-28 19:19 UTC, tekktrik requested changes
Nice catches!  Only thing I noticed is that `:returns:` should be `:return:` I believe.  I think that goes for all the uses of `:returns:` in this library, unfortunately.

2022-03-28 19:19 UTC, tekktrik commented on adafruit_wiznet5k/adafruit_wiznet5k_socket.py
> -        :returns a tuple (nbytes, address) where address is a tuple (ip, port)
I believe this should be `:return:`

2022-03-28 19:27 UTC, Neradoc commented
`:returns:` renders the same as `:return:` so I didn't touch them, but I agree, they should be consistent. I'll do that.

2022-03-28 19:37 UTC, tekktrik commented
> `:returns:` renders the same as `:return:` so I didn't touch them, but I agree, they should be consistent. I'll do that.

Oh, good to know!

2022-03-29 14:18 UTC, tekktrik commented
@Neradoc looks like the new black wants to reformat something, wanna run `pre-commit` again?

2022-03-29 14:22 UTC, tekktrik approved these changes

2022-03-29 14:23 UTC, merged