Update SimpleServer example to accept >1 connection
adafruit/Adafruit_CircuitPython_Wiznet5k pull request #88
Opened 2023-01-14 00:44 UTC by e28eta

While watching @FoamyGuy [stream](https://youtu.be/ipIN_g8mRXc?t=6657), I noticed the server code he was using only allowed a single client connection.

This moves the `accept()` call into the `while True` loop, leaving the server accepting connections as long as the `server` socket is valid.

My understanding of the existing example code:

1. Binds a socket to the hardcoded IP + port combo
2. Listens for incoming connections
3. Accepts a single connection
4. Enters `while True` loop
5. `recv` up to 1024 bytes
6. prints & echos those bytes back to the client
7. closes `conn` in [__exit__](https://github.com/adafruit/Adafruit_CircuitPython_Wiznet5k/blob/1b8ff4e48931722133a97090bce01c4795d64803/adafruit_wiznet5k/adafruit_wiznet5k_socket.py#L178-L180)
8. loops forever with closed `conn` socket, [receiving nothing and printing nothing](https://github.com/adafruit/Adafruit_CircuitPython_Wiznet5k/blob/1b8ff4e48931722133a97090bce01c4795d64803/adafruit_wiznet5k/adafruit_wiznet5k_socket.py#L400-L401) (this is undesirable)
9. microcontroller running the server must be restarted in order to receive a new connection.

After this PR, I expect the example code to:

1. Binds a socket to the hardcoded IP + port combo
2. Listens for incoming connections
3. Enters `while True` loop
4. Accepts a connection
5. `recv` up to 1024 bytes
6. prints & echos those bytes back to the client
7. close connection to that client
8. return to step 4, ready for another client to connect.

2023-01-14 00:47 UTC, anecdata commented
@e28eta what would you think about putting compatible client code in the PR, if not in some comments in the example code?

2023-01-14 03:32 UTC, anecdata requested changes
Also suggest changing line 21 init to remove `dhcp=False` since there's no static IP address set up with `eth.ipconfig` (IP address will be 0.0.0.0 without DHCP or static IP).

Tested successfully (with DHCP change) on:
```py
Adafruit CircuitPython 8.0.0-beta.6-25-gbb3a1c0a2 on 2023-01-04; Raspberry Pi Pico W with rp2040
```
with:
```py
# For Raspberry Pi Pico [W] with WIZnet Ethernet Hat
cs = digitalio.DigitalInOut(board.GP17)
spi_bus = busio.SPI(board.GP18, MOSI=board.GP19, MISO=board.GP16)
```
running CPython TCP client:
```py
#!/usr/bin/env python3
import socket
import time

# edit host and port to match server
HOST = "192.168.10.1"
PORT = 50007
TIMEOUT = 10
INTERVAL = 5
MAXBUF = 1024

while True:
    print("Create TCP Client Socket")
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.settimeout(TIMEOUT)
    print("Connecting")
    s.connect((HOST, PORT))
    size = s.send(b'A5'*512)
    print("Sent", size, "bytes")
    buf = s.recv(MAXBUF)
    print('Received', buf)
    s.close()
    time.sleep(INTERVAL)
```
There's no error-handling in client or server, but I think it makes the point for a simple test.

2023-01-21 07:01 UTC, e28eta commented
> @e28eta what would you think about putting compatible client code in the PR, if not in some comments in the example code?

I added your client, and a comment in that client with a `nc` version.

> Also suggest changing line 21 init to remove dhcp=False since there's no static IP address set up with eth.ipconfig (IP address will be 0.0.0.0 without DHCP or static IP).

I finally got a setup to test myself, and it looks like the `server.bind((server_ip, server_port))` call is sufficient to set the local IP (at least for that socket) to the provided `server_ip` constant.

> Tested successfully (with DHCP change) 

I don't have it setup to have a DHCP server running. However, I was able to test the code as it currently exists in this PR on:

```
Adafruit CircuitPython 7.3.3 on 2022-08-29; Adafruit Feather RP2040 with rp2040
Board ID:adafruit_feather_rp2040
```

and the [Adafruit Ethernet FeatherWing](https://www.adafruit.com/product/3201)

2023-01-21 07:04 UTC, e28eta commented
@anecdata  looks like the build is failing because I don't have licensing info in the (newly added) client you wrote. How would you like it licensed?

2023-01-21 13:41 UTC, anecdata commented
> @anecdata  looks like the build is failing because I don't have licensing info in the (newly added) client you wrote. How would you like it licensed?

Can you grab some Adafruit boilerplate? It doesn't matter to me, it's a simple thing I'm sure I pieced together from various examples.

2023-01-23 22:34 UTC, FoamyGuy approved these changes
This looks good to me now. Thanks again for working on this improvement @e28eta!

I added one commit to make the following tweaks:
- rename the new example. I think something somewhere assumes It will start with the "short name" of the repo. 
- Change the simpleserver to use DHCP, it can only work coincidentally if it already got an IP prior without this change. 
- add license information to the new example to make re-use happy.

2023-01-23 22:35 UTC, merged